# -----------------------------------------
#
# Getting Started Guide
# ---
# https://shopify.github.io/themekit/
#
# Example Executables
# ---
# `theme download --env=production`
# `theme watch --env=develop`
# `theme deploy --env=test`
#
# -----------------------------------------

production:
  theme_id: 75905859663
  password: 6635cdb15f95c5c445bf6ea5d3e5fa4a
  store: beckett-simonon.myshopify.com
  concurrency: 4
  timeout: 60s
  ignore_files:
    - "node_modules/*"
    - "config/settings_data.json"
    - "src/*"
    - .jshintignore
    - "*.sublime-workspace"
    - "*.sublime-project"
    - "package.json"
test:
  theme_id: 80062087215
  password: db3c441942a5c40d9af682e649c9659f
  store: development-beckett-simonon.myshopify.com
  concurrency: 4
  timeout: 3000s
  ignore_files:
    - "node_modules/*"
    - "config/settings_data.json"
    - "src/*"
    - .jshintignore
    - "*.sublime-workspace"
    - "*.sublime-project"
    - "package.json"
develop:
  theme_id: 51927842916
  password: f687d6025e23eb2addab926d9b4f4583
  store: bec-sin-dev.myshopify.com
  concurrency: 4
  timeout: 60s
  ignore_files:
    - "node_modules/*"
    - "src/*"
    - .jshintignore
    - "*.sublime-workspace"
    - "*.sublime-project"
    - "package.json"
